### ISSUE TITLE
Any plan to add documentation for arsenal?

### ISSUE THREAD

**Issue by PharrellWANG** [timvieira/arsenal#4]
Hi tim, 
Thanks for arsenal package, just want to ask do you have any plan to add documentation where usage examples would be given.

**Comment by timvieira** [comment]
I am open to some specific suggestions and/or pull requests 😀

The arsenal is almost entirely utility functions so doctest-style documentation is kind of ideal (since don't need to describe overarching design or anything like that). There are a bunch of doctests in there already.

However, doctests might not be "enough" - e.g. there is currently no means for new users to become oriented with what's even in the arsenal. Maybes the mostly auto-generated readthedocs strategy could work?

Thoughts?

**Comment by PharrellWANG** [comment]
When i was reading your blog for fast sigmoid sampling, I saw a type of timer class usage which has not been mentioned in doctests. 

I think, to expose the full power of arsenal to the public users, we need to have more doctests showing the potential usages. And the auto-generated readthedocs strategy will definitely work.

**Comment by timvieira** [comment]
Cool. I will look into setting up a readthedocs page based on Sphinx-autodoc.  As for the `Timer` class, did you figure out how to use it in the end?  The example given in the fast sigmoid-sampling article should give a sense of the basic functionality.  There are some fancier things in there, e.g., tracking runtime given features of the inputs (e.g., input size); this let's you plot the runtime as we vary those features (i.e., runtime vs. input size).

**Comment by TejasAvinashShetty** [comment]
Any progress?

**Comment by timvieira** [comment]
Unfortunately, no.  I'm afraid that this task is a bit too large of an undertaking for me since there is a ton of stuff in this library that I have accumulated over the course of 10+ years since I first created it.  That said, if there are some submodules that seem useful to you that I can help you figure out, let me know.

**Comment by timvieira** [comment]
I spent the morning getting a [https://python-arsenal.readthedocs.io/en/latest/[Read the Docs] page up and running for this project.  Hope this helps!
